"use client"
export const bundleData = [
  {
    id: 1,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/5.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 2,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/6.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 3,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/7.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 4,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/8.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
  {
    id: 5,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/9.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 6,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/10.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 7,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/11.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 8,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/12.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
  {
    id: 9,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/13.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 10,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/14.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 11,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/15.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 12,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/16.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
];

export const bundleDataTwo = [
  {
    id: 1,
    slug: '/Chapter/Light?ProductTypes=1',
    image: '/assets/allCat/svet.png',
    title: 'Свет',
    description: '10000',
    bgColor: '#FFEED6',
  },
  {
    id: 2,
    slug: '/Chapter/Furniture?ProductTypes=2',
    image: '/assets/allCat/mebel.png',
    title: 'Мебель',
    description: '10000',
    bgColor: '#D9ECD2',
  },
  {
    id: 3,
    slug: '/Chapter/Mirrors?ProductTypes=3',
    image: '/assets/allCat/zerkala.png',
    title: 'Зеркала',
    description: '10000',
    bgColor: '#DBE5EF',
  },
  {
    id: 4,
    slug: '/Chapter/Carpets?ProductTypes=4',
    image: '/assets/allCat/carpets.png',
    title: 'Ковры',
    description: '10000',
    bgColor: '#EFD8D4',
  },
  {
    id: 5,
    slug: '/Chapter?ProductTypes=5',
    image: '/assets/allCat/acsess2.png',
    title: 'Картины и аксессуары',
    description: '10000',
    bgColor: '#EFD8D4',
  },
  {
    id: 6,
    slug: '/Chapter/GoodsForHome?ProductTypes=6',
    image: '/assets/allCat/dom2.png',
    title: 'Товары для дома',
    description: '10000',
    bgColor: '#EFD8D4',
  },
];
export const bundleDataThree = [
  {
    id: 1,
    slug: 'your-premium-tissue-paper-collection',
    image: '/assets/images/bundle/17.png',
    title: 'bundle-title-five',
  },
  {
    id: 2,
    slug: 'stay-strong-with-healthy-breakfast-everyday',
    image: '/assets/images/bundle/18.png',
    title: 'bundle-title-six',
  },
  {
    id: 3,
    slug: 'be-fit-and-healthy-with-diet-food-choice',
    image: '/assets/images/bundle/19.png',
    title: 'bundle-title-seven',
  },
];
